
<h1>gestion admin</h1>

<nav class=admin_nav>
    <li class="nav_item_admin"><a href="index.php?page=admin&addarticle"/>Création</a></li>
    <li class="nav_item_admin"><a href="index.php?page=admin&change">Modification</a></li>
    <li class="nav_item_admin"><a href="index.php?page=admin&delete">Suppression</a></li>
    <li class="nav_item_admin"><a href="index.php?page=admin&deleteUser">gestion d'utilisateur</a></li>
    <li class="nav_item_admin"><a href="index.php?page=admin&newsletter">Newsletters</a></li>
</nav>


<!--***************************************************-->
<!--*-->
<!--*                creation-->
<!--*-->
<!--***************************************************-->



<!--upload image -->
<?php
if(isset($_GET['addarticle'])): ?>
    <h2>creation d'articles</h2>
    
        <div class='form-'>
            <h4>Envoi d'une image</h4>
            <p>Choisissez une image sur votre ordinateur (max de 3mo) puis vous cliquer sur envoyer. Ensuite votre image s'affichera au dessus du formulaire à remplir.</p>
        
        
            <section id="envoiImage">
                <form class="form-group" method="post"  enctype="multipart/form-data">
                    <input type="file" name="<?= $nameOfInputUpload ?>"/>
                    <button type ="submit" id="btn"> Envoyer </button>
                 </form>   
                 
                    <?php if($isPost): ?>
                        <div class='modal'>
                            <?= $isPost ? $message : null ?>
                        <?php endif ?>
                        </div>
            </section>
        </div>
    

        <section id="affichageImage"> 
            <?php if ($isPost && isset($urlImage)): ?>
                <img  src= <?= $urlImage ?> alt='une image chargée' /> 
            <?php endif ?>
        </section>
    
    
        <?php if($validFile): ?>
            <form class="form-group" method='POST'>+
                <?=$Article->input('title')?>
                <?=$Article->textarea('text', 'text')?>
                <?=$Article->submit()?>
            </form>
        
            
            <?php if(isset($_POST['Envoyer'])): ?>
                <div class='modal'>
                        <p class="modal_text"><i>Article créé !</i></p>
                </div>        
            <?php endif ?>
                
        <?php endif ?>
        
<?php endif ?>



<!--***************************************************-->
<!--*-->
<!--*               modification articles-->
<!--*-->
<!--***************************************************-->


<!--select the articles for mod.-->
<?php 
if(isset($_GET['change'])): ?>
    <h2>modifier un article</h2>
    <p>Selection l'article a modifier</p>
    
    <!--select the title of article for mod.-->
        
        <form class="form-group" method='POST'>
            <?=$Article->selectorForeach('id', $titleForEdit)?>
            <?=$Article->submit()?>
        </form>
        
        <?php if(isset($_POST['Envoyer'])): ?>
            
            <div class='modal'>
                <p>Vous Pouvez changer le titre et le contenu de l'article</p>
            </div>

            <form class ="form-group" method='POST'>
                <?=$Article->input('title')?>
                <?=$Article->textarea('text', 'text')?>
                <?=$Article->submit('Valider')?>
            </form>
            
         <?php endif ?>   
         
         <?php if(isset($_POST['Valider'])): ?>
             <div class='modal'>
                <p>Article modifié</p>
            </div>
        <?php endif ?>
            
          
        
<?php endif ?>




<!--***************************************************-->
<!--*-->
<!--*                delete-->
<!--<!-*-->
<!--***************************************************-->


<?php 
if(isset($_GET['delete'])): ?>

    <h2>Supprimer un article</h2>
    <!--select the title of article for mod.-->
    
        <form class ="form-group" method='POST'>
            <p><i>Sélectionner l'article à supprimer </i></p>
            <?=$Article->selectorForeach('id', $titleForEdit)?>
            <?=$Article->submit()?>
        </form>   
        
        
        <?php if(isset($_POST['Envoyer'])): ?>
            <div class='modal'>
            <p class="modal_text"><i>L'article à été supprimé </i></p>
            <?php endif ?>
            </div>
      
<?php endif ?>


<!--***************************************************-->
<!--*-->
<!--*             <gestion utilisateur>-->            
<!--<!-*-->
<!--***************************************************-->

<?php
    if(isset($_GET['deleteUser'])): ?>
        <h2>Gestion utilisateurs</h2>
        
            <table>
                 <thead>
                     <tr>
                         <th colspan="3">liste des utilisateurs</th>
                     </tr>         
                </thead>
                
                 <tbody>
                     <tr>
                            <?php foreach ($listUsers as $listUser){
                                $listUsers['username'] = $listUser['username'];
                                // $listUser['mail']                      
                            }
                            ?>
                            
                                <td> <?php $listUser['username'] ?> </td>
                              <td> <?php $listUser['mail'] ?></td>
                                <td></td>
                     </tr>
                 </tbody>
             </table>


    <?php endif ?>

<!--***************************************************-->
<!--*-->
<!--*             </newsletter>-->            
<!--<!-*-->
<!--***************************************************-->

<?php

if(isset($_GET['newsletter'])): ?>
    <h2>Création d'une newsletter</h2>
    
        <form class ="form-group" method='POST'>
            <p><i>Rédaction</i></p>
            <?=$Article->input('title')?>
            <?=$Article->imput('mail', 'email')?>
            <?=$Article->textarea('text', 'text')?>
            <?=$Article->submit('Envoyer')?>
        </form>   
        
        
        <?php if(isset($_POST['Envoyer'])): ?>
            <div class='modal'>
            <p class="modal_text"><i>La newsletter est partie </i></p>
            <?php endif ?>
            </div>
            
<?php endif ?>

