
<h2>Connexion</h2>

  
<form class="form-group" method='POST'>
    <?=$myForm->input('mail','email')?>
    <?=$myForm->input('password', 'password')?>
    <?=$myForm->submit()?>
</form>

<?php if(isset($_POST['Envoyer'])): ?>
    <div class='modal'> 
        <p class="modal_text"><i><?= $passLength ?></i></p>
        <p class="modal_text"><i><?= $mailLength ?></i></p>
        <p class="modal_text"><i><?= $validationMail ?></i></p>
        <p class="modal_text"><i><?= $connexion ?></i></p>
    </div> 
<?php endif ?> 

