
<h2>Nous contacter</h2>

<form class="form-group" method='POST' action="#">
    <?=$myForm->input('name')?>
    <?=$myForm->input('mail', 'email')?>
    <?=$myForm->input('objet')?>
    <?=$myForm->textarea('message')?>
    <?=$myForm->submit()?>
</form>

     
<?php if(isset($_POST['Envoyer']) && !empty($_POST['Envoyer'])): ?>
    <div class='modal'>
        <p> <?= $msgOk ?></p>
        <p class="modal_text"> Message envoyé</p>
        <button class="btn"><a href='https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php'>Accueil</a></button>
    </div>    
    <?php endif ?>
     

<?= $nameLength ?>
<?= $mailLength ?>
<?= $objetLength ?>
<?= $msgLength ?>