<h2>Dons</h2>

<div class="wrapper_don">
    <div class="card_don" >
        
        <div class="card_don_text" >
            <p>Vous pouvez nous faire un <strong>don</strong> et nous vous en remercions!</p>
            
            <a href="https://www.paypal.com/" target="_blank" title=Paypal><i class="fa-brands fa-paypal"></i></a>
            
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, ea, odio obcaecati omnis exercitationem reprehenderit illo doloribus optio consectetur ipsam.
            </p>
        </div>
        
    </div>
</div>    