        <footer>
            <div class="container_footer">
                <div id="logo_footer"><a href="index.php"><img class="img_logo_footer"  src="vendor/images/logo.png" alt="Logo"></a>
                </div>
                <div class="menuAcc">
                    <div class="toggleAcc btn" title="menu accessibilité">
                        <i class="fa-solid fa-universal-access"></i>
                    </div>
                    <div id="acc">
                        <div class="acc_font">
                            <a href="#" class="acc__font_min" title="Diminuer la taille de police" id='sizeDown'><strong> A- </strong></a>
                            <a href="#" class="acc__font_reset" title="taille de police par défaut" id='sizeDefault'> <strong> A </strong></a>
                            <a href="#" class="acc__font_up" title="Augmenter la taille de la police" id='sizeUp'> <strong> A+ </strong></a>
                        </div>             	
                        <button id="theme-toggle">
                            <i class="fas fa-moon"></i>
                        </button>
                    </div>
                </div> 
    
                <div class="info">
                    <a title ="Notre Staff" href="index.php?page=propos"><h3>A propos</h3></a>
                    <p>Association trisomie 21</p>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione ullam p ex nostrum?</p>
                </div>
    
                <div class="social">
                    <a href="https://www.instagram.com/" target="_blank" title="Instagram"><i class="fa-brands fa-instagram"></i></a>
                    <a href="https://www.facebook.com/" target="_blank" title="Facebook"><i class="fa-brands fa-facebook"></i></a>
                    <a href="https://www.youtube.com/" target="_blank" title="Youtube"><i class="fa-brands fa-youtube"></i></a>
                </div>
            </div>
        </footer> 
    
        <script src="vendor/Javascript/app.js"></script>
    </body>
</html>