    <footer>
        <div class="container_footer">
            <div id="logo_footer"><a href="index.html"><img class="img_logo_footer"  src="vendor/images/logo.png" alt="Logo"></a>
            </div>

            <div class="info">
                <a href="#" target="_blank"><h3>A propos</h3></a>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione ullam perspiciatis nesciunt excepturi dolores laudantium voluptates maiores ipsa facere ex nostrum placeat, eos ut sint veniam, quod incidunt! Eum, sunt?</p>
            </div>

            <div class="social">
                <a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram "></i> Instagram</a>
                <a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook-f"></i> Facebook</a>
                <a href="https://www.youtube.com/" target="_blank"><i class="fa-brands fa-youtube"></i> Youtube</a>
            </div>
        </div>
    </footer>

    <button id="btn"><a href="#"></a></button>
    <script src="vendor/Javascript/app.js"></script>
</body>
</html>