<!DOCTYPE html>
<html lang="fr">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="/vendor/CSS/style.scss">
    <link rel="stylesheet" href="vendor/CSS/style.css">
    <link rel="stylesheet" href="vendor/CSS/tools.scss">
    <link rel="stylesheet" href="vendor/CSS/tools.css">
    <link rel="shortcut icon" type="image/png" href="vendor/images/logo.png"/>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Un truc en + ! </title>
</head>

<body>

    <header>
        <div class="container_header">
            <div class="toggle">
                <i class="fa-solid fa-bars ouvrir"></i>
                <i class="fa-solid fa-xmark fermer"></i>
            </div>

            <div id="logo_header"><a href="index.html"><img class="img_logo"  src="vendor/images/logo.png" alt="Logo"></a>
            </div>

            <nav id="nav_bar">
                <ul class="nav_list">
                   <li id="logo"><a href="index.html"><img class="img_logo"  src="vendor/images/logo.png" alt="Logo"></a></li>
                   <li class="nav_item"><a href="https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=article">Actualités</a></li>
                   <li class="nav_item"><a href="https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=propos">A propos</a></li>
                   <li class="nav_item"><a href="https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=contact">Nous contacter </a></li>
                   <li class="nav_item"><a href="https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=donation">Donation</a></li>
                   <li><a href="https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=connexion"><button class="btn_co" role="button">Connexion</button></a></li>
                   <li><a href"https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=register"><button class="btn_register" role="button" >Inscription</button></a></li> 
                </ul>
            </nav>
        </div> 
    </header>
    
