<!DOCTYPE html>
<html lang="fr">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css" type="text/css" />
    <link rel="stylesheet" href="vendor/CSS/style.scss"/>
    <link rel="stylesheet" href="vendor/CSS/style.css"/>
    <link rel="shortcut icon" type="image/png" href="vendor/images/logo.png"/>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Un truc en + ! </title>
</head>

<body class="theme">
    <header>
        <div class="container_header">
                <div class="logo_header"><a title="logo" href="index.php"><img class="img_logo_header" src="vendor/images/logo.png" alt="Logo"></a>
                </div>
                
                <div class="hamburger">
                    <i class="fa-solid fa-bars menuIcon"></i>
                    <i class="fa-solid fa-xmark closeIcon"></i>
                </div>
                    
            <nav class="nav_bar">        
                <ul class="menu">
                    <li class="logo"><a title="logo" href="index.php"><img class="img_logo"  src="vendor/images/logo.png" alt="Logo"></a></li>
                    <li class="menuItem"><a title="Actualités" href="index.php?page=article">Actualités</a></li>
                    <li class="menuItem"><a title="STAFF" href="index.php?page=propos">L'asso</a></li>
                    <li class="menuItem"><a title="Contact" href="index.php?page=contact">Contact </a></li>
                    <li class="menuItem"><a title="Don" href="index.php?page=donation">Donation</a></li>
                        <?php if(isset($_SESSION['user']) && $_SESSION['role'] === 1) : ?>
                        <li class="menuItem"><a title="Admin" href="index.php?page=admin">Admin</a></li>
                        <?php endif ?>
                        <?php if(!isset($_SESSION['user']) || empty($_SESSION['user'])) : ?>
                            <li class="menuItem_btn_co">
                                <a title="Connexion" href="index.php?page=connexion">
                                    <button class="btn_co" name="btn_co">Connexion</button>
                                </a>
                            </li>
                            <li class="menuItem_btn_register"><a href="index.php?page=register" title="Inscription"><button class="btn_register" name="btn_register">Inscription</button></a></li>
                        <?php else : ?>
                    <li><a href="index.php?page=disconnect" title="deconnexion" ><i class="fa-solid fa-right-from-bracket"></i></a></li>
                        <?php endif ?> 
                </ul>
            </nav>
            <!--<div class="menuAcc">-->
            <!--    <div class="toggleAcc btn" title="menu accessibilité">-->
            <!--        <i class="fa-solid fa-universal-access"></i>-->
            <!--    </div>-->
            <!--    <div id="acc">-->
            <!--        <div class="acc_font">-->
            <!--            <a href="#" class="acc__font_min" title="Diminuer la taille de police" id='sizeDown'><strong> A- </strong></a>-->
            <!--            <a href="#" class="acc__font_reset" title="taille de police par défaut" id='sizeDefault'> <strong> A </strong></a>-->
            <!--            <a href="#" class="acc__font_up" title="Augmenter la taille de la police" id='sizeUp'> <strong> A+ </strong></a>-->
            <!--        </div>             	-->
            <!--        <button id="theme-toggle">-->
            <!--            <i class="fas fa-moon"></i>-->
            <!--        </button>-->
            <!--    </div>-->
            <!--</div>    -->
        </div>
    </header>
    