
    <main>
        <div class="container_main">

            <h1>Un truc en + !</h1>

            <div class="containerCTA">
                <div class="containerCTA_picture">
                    <!--
                    <img class="containerCTA_picture_pompom" src="vendor\images\pompom\pexels-rodnae-productions-7402833.jpg" alt="pompom-girl_disease_explanation">
                    
                </div>
                 -->   
                <div class="containerCTA_text">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates harum nisi enim laudantium facilis, repellendus voluptatibus totam pariatur iure dolorum labore, et ullam id quaerat natus deserunt alias consectetur! Earum!</p>
                    
                    <!-- creation d une div pour cacher les paragraphes de trop en mobile-->
                    <!--<div class="p_none"> -->
                    <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates harum nisi enim laudantium facilis, repellendus voluptatibus totam pariatur iure dolorum labore, et ullam id quaerat natus deserunt alias consectetur! Earum!</p>-->
                    <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates harum nisi enim laudantium facilis, repellendus voluptatibus totam pariatur iure dolorum labore, et ullam id quaerat natus deserunt alias consectetur! Earum!</p>     -->
                    <!--</div>        -->
                </div>

            </div>  
        </div>

        <div class="container_under_CTA">
            <section>
                <div class="container_section">
                    <article>
                        <div class="article_first">
                            <div class="article_first_picture">
                                <a href="https://alexandrevallon.sites.3wa.io/projet3WA-main/index.php?page=article"><img loading="lazy" class="article_first_janeDoe" src="vendor/images/nouveau/janeDoe.jpg" alt="article_picture"></a>  <!--loading lazy -->
                            </div>
    
                            <div class="article_first_text">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>
                                <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>-->
                                <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>-->
                            </div>
                        </div>
    
                    </article>
                    
                    <article>
                        <div class="article_first">
                            <div class="article_first_picture">
                                <img loading="lazy" class="article_first_janeDoe" src="vendor/images/nouveau/janeDoe.jpg" alt="article_picture"> <!--loading lazy increase the optimization of performances-->
                            </div>
    
                            <div class="article_first_text">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>
                                <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>-->
                                <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>-->
                            </div>
    
                        </div>
                    </article>
                    
                    <article>
                        <div class="articlenonetablet">
                            <div class="article_first">
                                <div class="article_first_picture">
                                    <img loading="lazy" class="article_first_janeDoe" src="vendor/images/nouveau/janeDoe.jpg" alt="article_picture"> <!--loading laszy permet le retardement des pics-->
                                </div>
    
                                <div class="article_first_text">
                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>
                                    <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>-->
                                    <!--<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum?</p>-->
                                </div>
                           </div>
                        </div>   
                    </article>
    
                </div>
                
            </section>
        </div>
    </main>
    
