<main class="wrapper">
    <div class="container_main">
        <div class="wrap_h1">
            <h1>Un truc en + !</h1>
        </div>
        
        
        <div class="menuAcc">
                <div class="toggleAcc btn" title="menu accessibilité">
                    <i class="fa-solid fa-universal-access"></i>
                </div>
                <div id="acc">
                    <div class="acc_font">
                        <a href="#" class="acc__font_min" title="Diminuer la taille de police" id='sizeDown'><strong> A- </strong></a>
                        <a href="#" class="acc__font_reset" title="taille de police par défaut" id='sizeDefault'> <strong> A </strong></a>
                        <a href="#" class="acc__font_up" title="Augmenter la taille de la police" id='sizeUp'> <strong> A+ </strong></a>
                    </div>             	
                    <button id="theme-toggle">
                        <i class="fas fa-moon"></i>
                    </button>
                </div>
            </div>
        
        
        
        <div class="containerCTA">
            <div class="containerCTA_picture">                
                <div class="containerCTA_text">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates harum nisi enim laudantium facilis, repellendus voluptatibus totam pariatur iure dolorum labore, et ullam id quaerat natus deserunt alias consectetur! Earum!</p>
                </div>
            </div>  
        </div>
        <div class="container_under_CTA">
            <section>
                <div class="container_section">
                    <div class="container_blockMission">
                        <div class="container_section_block">
                            <article>
                                <div class="blockMission">
                                    <p class="blockquote"><i class="fa-solid fa-quote-left"></i></p>
                                    <h4><strong>Soutien et accompagnement des familles.</strong></h4>
                                    <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                    sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                                    magna aliquam erat volutpat.</p>
                                </div>
                            </article>
                            
                            <article>
                                <div class="blockMission">
                                    <p class="blockquote"><i class="fa-solid fa-quote-left"></i></p>
                                    <h4><strong>Organisation de moments festifs.</strong></h4>
                                    <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                    sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                                    magna aliquam erat volutpat.</p>
                                </div>
                            </article>
                        </div>    
                        <div class="container_section_block">
                            <article>
                                <div class="blockMission">
                                    <p class="blockquote"><i class="fa-solid fa-quote-left"></i></p>
                                    <h4><strong>Aide administrative.</strong></h4>
                                    <p>  Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                    sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                                    magna aliquam erat volutpat.</p>
                                </div>
                            </article>
                            <article>
                                <div class="blockMission">
                                    <p class="blockquote"><i class="fa-solid fa-quote-left"></i></p>
                                    <h4><strong>Sensibilité du corps médical.</strong></h4>
                                    <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                    sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                                    magna aliquam erat volutpat.</p>
                                </div>
                            </article>
                        </div>
                    </div>
                    <h3>Nos dernières actualités</h3>
                    <div class="container_section_block">
                        <article class="containerArticle">
                            <div class="article_first">
                                <div class="article_first_picture">
                                    <a href="index.php?page=article"><img loading="lazy" class="article_first_janeDoe" src="vendor/images/nouveau/article.jpg" alt="article_picture"></a>  <!--loading lazy -->
                                </div>
                                <div class="article_first_text">
                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus blanditiis in, ipsam quidem quae nostrum? </p>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>