<h2>Le staff</h2>

<section class="container_staff">
    
    <article>
        <div class="card_staff">
            <div class="card_staff_img"><img src="vendor/images/staff/granny.jpg" class="img_staff"></img></div>
                <div class="card_staff_text">
                    <p>Lorum Ipseum</p>
                    <p><strong>Présidente</strong></p>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,sed.</p>
                </div>
        </div>
        
        <div class="card_staff">
            <div class="card_staff_img"><img src="vendor/images/staff/jane.jpg" class="img_staff"></img></div>
                <div class="card_staff_text">
                    <p>Lorum Ipseum</p>
                    <p><strong>Secretaire</strong></p>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                    sed.</p>
                </div>       
        </div>    
        <div class="card_staff">
            <div class="card_staff_img"> <img src="vendor/images/staff/bob.jpg" class="img_staff"></img></div>
                <div class="card_staff_text">
                    <p>Lorum Ipseum</p>
                    <p><strong>Trésorier</strong></p>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                    sed.</p>
                </div>
        </div>
    </article>
    
    <article>
        <div class="about">
            <h4>Démarche et conseil</h4> 
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                magna aliquam erat volutpat. Ut wisi enim ad minim veniam,
                quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                ut aliquip ex ea commodo consequat. Duis autem vel eum iriure
            </p>
            <p>
                dolor in hendrerit in vulputate velit esse molestie consequat,
                vel illum dolore eu feugiat nulla facilisis at vero eros et
                accumsan et iusto odio dignissim qui blandit praesent luptatum
                zzril delenit augue duis dolore te feugait nulla facilisi.
                Nam liber tempor cum soluta nobis eleifend option congue
                nihil imperdiet doming id quod mazim placerat facer possim
                assum. Typi non habent claritatem insitam; est usus legentis
                in iis qui facit eorum claritatem. Investigationes
                demonstraverunt.
            </p>
            <p>
                 lectores legere me lius quod ii legunt saepius.
                Claritas est etiam processus dynamicus, qui sequitur mutationem
                consuetudium lectorum. Mirum est notare quam littera gothica,
                quam nunc putamus parum claram, anteposuerit litterarum formas
                humanitatis per seacula quarta decima et quinta decima. Eodem
                modo typi, qui nunc nobis videntur parum clari, fiant sollemnes
                in futurum.
            </p>
        </div>
        
    </article>
    
</section>