

<h1> Notre staff</h1>

<div class="container_staff">
    
    <div class="card_staff">
        <div class="card_staff_img"> <img src="vendor/images/staff/granny.jpg"></img> </div>
        <div class="card_staff_text">
            <p>Lorum Ipseum</p>
            <p>notre président</p>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
            sed.</p>
        </div>
    </div>
    
    <div class="card_staff">
        <div class="card_staff_img"><img src="vendor/images/staff/pamela.jpg"></img></div>
            <div class="card_staff_text">
                <p>Lorum Ipseum</p>
                <p>notre président</p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                sed.</p>
            </div>
        </div>
        
    <div class="card_staff">
        <div class="card_staff_img"> <img src="vendor/images/staff/bob.jpg"></img></div>
        <div class="card_staff_text">
            <p>Lorum Ipseum</p>
            <p>notre président</p>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
            sed.</p>
        </div>
    </div>
    

</div>
